// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDeployModel = "deploy"

// DeployModel mapped from table <deploy>
type DeployModel struct {
	ID            int            `gorm:"column:id;primaryKey;autoIncrement:true"`
	Name          string         `gorm:"column:name;comment:部署标题"`           // 部署标题
	ProjectID     int            `gorm:"column:project_id;comment:项目ID"`     // 项目ID
	Project       string         `gorm:"column:project;comment:项目"`          // 项目
	TemplateID    int            `gorm:"column:template_id;comment:项目模板"`    // 项目模板
	Template      string         `gorm:"column:template;comment:模板"`         // 模板
	TemplateParse string         `gorm:"column:template_parse;comment:模板解析"` // 模板解析
	Params        string         `gorm:"column:params;comment:模板变量"`         // 模板变量
	Status        int            `gorm:"column:status;comment:状态"`           // 状态
	CreateTime    time.Time      `gorm:"column:create_time;default:CURRENT_TIMESTAMP"`
	UpdateTime    time.Time      `gorm:"column:update_time;default:CURRENT_TIMESTAMP"`
	DeleteTime    gorm.DeletedAt `gorm:"column:delete_time"`
}

// TableName DeployModel's table name
func (*DeployModel) TableName() string {
	return TableNameDeployModel
}
