// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameK8sTemplateModel = "k8s_template"

// K8sTemplateModel 模板管理
type K8sTemplateModel struct {
	ID         int            `gorm:"column:id;primaryKey;autoIncrement:true"`
	Name       string         `gorm:"column:name;comment:模板名"`     // 模板名
	Desc       string         `gorm:"column:desc;comment:模板描述"`    // 模板描述
	Content    string         `gorm:"column:content;comment:模板内容"` // 模板内容
	CreateTime time.Time      `gorm:"column:create_time;default:CURRENT_TIMESTAMP"`
	UpdateTime time.Time      `gorm:"column:update_time;default:CURRENT_TIMESTAMP"`
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time"`
}

// TableName K8sTemplateModel's table name
func (*K8sTemplateModel) TableName() string {
	return TableNameK8sTemplateModel
}
