// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProjectModel = "project"

// ProjectModel 项目表
type ProjectModel struct {
	ID         int            `gorm:"column:id;primaryKey;autoIncrement:true"`
	Name       string         `gorm:"column:name;comment:项目名"`         // 项目名
	Desc       string         `gorm:"column:desc;comment:项目描述"`        // 项目描述
	Git        string         `gorm:"column:git;comment:git地址"`        // git地址
	UserName   string         `gorm:"column:user_name;comment:用户名"`    // 用户名
	Token      string         `gorm:"column:token;comment:令牌/密码"`      // 令牌/密码
	UseTag     int            `gorm:"column:use_tag;comment:是否使用 TAG"` // 是否使用 TAG
	CreateTime time.Time      `gorm:"column:create_time;default:CURRENT_TIMESTAMP"`
	UpdateTime time.Time      `gorm:"column:update_time;default:CURRENT_TIMESTAMP"`
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time"`
}

// TableName ProjectModel's table name
func (*ProjectModel) TableName() string {
	return TableNameProjectModel
}
