// Code generated by goctl. DO NOT EDIT.
package websocket

import (
	"k8s-deploy/handler/websocket"

	"github.com/gin-gonic/gin"
)

func RegisterWebsocketRoute(e *gin.Engine) {
	g := e.Group("")
	g.GET("/websocket", websocket.WebsocketHandle)
}
