// Code generated by goctl. DO NOT EDIT.
package ui

import (
	"k8s-deploy/handler/ui"

	"github.com/gin-gonic/gin"
)

func RegisterUiRoute(e *gin.Engine) {
	g := e.Group("")
	g.GET("/", ui.UiHandle)
}
