// Code generated by goctl. DO NOT EDIT.
package deploy

import (
	"k8s-deploy/handler/deploy"
	"k8s-deploy/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterDeployRoute(e *gin.Engine) {
	g := e.Group("")
	g.Use(middleware.JwtMiddleware, middleware.AuthMiddleware)
	g.GET("/deploy", deploy.ListHandle)
	g.POST("/deploy", deploy.AddHandle)
	g.POST("/deploy/deploy/:id", deploy.DeployHandle)
	g.DELETE("/deploy/:id", deploy.DelHandle)
}
