// Code generated by goctl. DO NOT EDIT.
package template

import (
	"k8s-deploy/handler/template"
	"k8s-deploy/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterTemplateRoute(e *gin.Engine) {
	g := e.Group("")
	g.Use(middleware.JwtMiddleware, middleware.AuthMiddleware)
	g.GET("/template", template.ListHandle)
	g.POST("/template", template.AddHandle)
	g.PUT("/template/:id", template.EditHandle)
	g.DELETE("/template/:id", template.DelHandle)
}
