// Code generated by goctl. DO NOT EDIT.
package auth

import (
	"k8s-deploy/handler/admin/auth"
	"k8s-deploy/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterAdminAuthRoute(e *gin.Engine) {
	g := e.Group("")
	g.Use(middleware.JwtMiddleware, middleware.AuthMiddleware)
	g.GET("/auth", auth.ListHandle)
	g.POST("/auth", auth.AddHandle)
	g.PUT("/auth/:id", auth.EditHandle)
	g.DELETE("/auth/:id", auth.DelHandle)
}
