// Code generated by goctl. DO NOT EDIT.
package project

import (
	"k8s-deploy/handler/project"
	"k8s-deploy/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterProjectRoute(e *gin.Engine) {
	g := e.Group("")
	g.Use(middleware.JwtMiddleware, middleware.AuthMiddleware)
	g.GET("/project", project.ListHandle)
	g.POST("/project", project.AddHandle)
	g.PUT("/project/:id", project.EditHandle)
	g.DELETE("/project/:id", project.DelHandle)
}
